Suggestions Api is created
neon-lab-dev/product-service pull request #23
Opened 2024-04-29 10:24 UTC by sjha24

1. Create Suggestion

2024-05-01 00:27 UTC, neon-lab-dev requested changes

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/apis/DeleteSuggestionApi.java
> +    SuggestionService suggestionService;
Make it private

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/service/SuggestionService.java
> +    public ApiOutput<List<SuggestionDto>> fetchSuggestion() throws InvalidInputException, ServerException {
*Naming Convention*

- The method `fetchSuggention` is in *SuggetionService*.  
- Motive of giving the name is to communicate the operation it's doing. 
- Here, `fetchSuggestion` tells to get the list of suggestions. 
- The same thing can all be communicated by `suggestionService.fetch`

In an Office, a person's work is only to maintain the in and outs of employees in a record. 
If you want him to give the record, you will say `person.record` and not `person.inAndOutRecord`. But if you are asking him some other record that is out of his `concern` then you need to explicitly define which like `person.someOtherRecord`.

cc- @sjha24

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/service/SuggestionService.java
> +    public ApiOutput<List<SuggestionDto>> fetchSuggestion() throws InvalidInputException, ServerException {
Service layer should not give ApiOut put . This is the concern of the Api layer and not service layer.

Give normal output. Attach that to the ApiOutput in the API layer.

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/apis/SuggestionApi.java
> +    SuggestionService suggestionService;
Make these private

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/controller/SuggestionController.java
> +        return suggestionApi.createSuggestion(suggestionDto);
Refer to the `Naming Convention` comment.

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/dtos/BoughtProductDetailsDto.java
>  @Data
Add `@JsonIgnoreProperties(ignoreUnknown = true)`

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/dtos/SuggestionDto.java
> +    String id;
add 
- createdAt
- createdBy
- ModifiedAt
- ModifiedBy

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/dtos/SuggestionDto.java
> +    String id;
These should be the part of the response.

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/entities/Suggestion.java
> +    private String comment;
Use `@Column` make it as not nullable

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/models/responses/PageableResponse.java
> -
Why?

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/service/OrderService.java
> +        List<BoughtProductDetailsDto> boughtProductsDetailsList = new ArrayList<>();
Learn using `var`

2024-05-01 00:27 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/service/SuggestionService.java
> +    public ApiOutput<SuggestionDto> createSuggestion(SuggestionDto suggestionDto) throws ServerException, InvalidInputException {
ApiOut is a part of API layer and not service layer.

cc- @sjha24

2024-05-02 03:58 UTC, neon-lab-dev requested changes

2024-05-02 03:58 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/apis/SuggestionApi.java
> +            return new ApiOutput<>(HttpStatus.OK.value(),"Thank Your for giving me suggestion" ,suggestionService.create(suggestionDto));
Thank you for your suggestions

2024-05-02 03:58 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/apis/FetchSuggestionApi.java
> +            return new ApiOutput<>(HttpStatus.OK.value(), "Your All Suggestion is below",suggestionService.fetch());
Suggestion List

2024-05-02 03:58 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/controller/SuggestionController.java
>      @PostMapping("/create")
Define roles permission

2024-05-02 03:58 UTC, neon-lab-dev commented on src/main/java/com/neonlab/product/controller/SuggestionController.java
Missing implementation for fetchall for admin only.

2024-05-02 14:56 UTC, ritik-agrawal requested changes, later dismissed

2024-05-02 14:56 UTC, ritik-agrawal commented on src/main/java/com/neonlab/product/apis/CancelOrderApi.java
> +    public ApiOutput<?> cancelById(String orderId) {
Undo this previous was correct.

2024-05-02 14:56 UTC, ritik-agrawal commented on src/main/java/com/neonlab/product/apis/CancelOrderApi.java
> +    public ApiOutput<?> cancelById(String orderId) {
make it simply cancel

2024-05-02 14:56 UTC, ritik-agrawal commented on src/main/java/com/neonlab/product/dtos/SuggestionDto.java
> +    Date createdAt;
private

2024-05-02 14:56 UTC, ritik-agrawal commented on src/main/java/com/neonlab/product/dtos/SuggestionDto.java
> +    Date createdAt;
comment v private hoga

2024-05-04 11:05 UTC, neon-lab-dev approved these changes

2024-05-04 11:06 UTC, merged